### ISSUE TITLE
Possibility to implement waterfall style(Pinterest-like) with the CompositionalLayoutSectionProvider closure?

### ISSUE THREAD

**Issue by Jinya** [defagos/SwiftUICollection#10]
Thanks for the nice attempt to integrate `UICollectionView` with SwiftUI.

I've recently been writing a waterfall page in SwiftUI (similar to Pinterest), and rather than using a series of hacks, I prefer to plug the native `UICollectionView` into the SwiftUI View, as you did before.

But I haven't found an efficient way to use the new API `UICollectionViewCompositionalLayoutSectionProvider` closure to achieve a perfect waterfall page, and I wonder if you have some ideas or thoughts to achieve it. Much appreciated for your reply.

**Comment by defagos** [comment]
I am not sure that the compositional layout API is the best choice when your layout depends on the size declared by the items to be displayed (which I assume is what you mean by Pinterest-like layout). AFAIK the compositional layout API can be used to describe a layout based on absolute sizes or on relative sizes between layout levels (groups and nested groups), but in a way that does not rely on the data to be displayed itself.

In your case I am therefore not convinced that using the compositional layout section provider (and thus my implementation of a SwiftUI collection) is a viable approach. You probably need a custom `UICollectionViewLayout` subclass implementing your content-based layout, and assigned to a `UICollectionView` you display directly.

This does not mean that you have to give up SwiftUI entirely, though. You can namely design cells in SwiftUI and wrap them into UIKit (as I do in my SwiftUI collection view implementation). Your collection view itself can be wrapped into SwiftUI as well (using `UIViewControllerRepresentable` or `UIViewRepresentable`) for display. Collection view updates can be triggered by an `ObservableObject` view model in a reactive fashion if you apply updates through a diffable data source. But of course this is more work you might have expected in the first place, and maybe what you mean by _series of hacks_.

If you are interested I can try to sketch this idea a bit more, but this is something that would deserve an entire article to be properly discussed. This is the approach we use in [our app](https://github.com/SRGSSR/playsrg-apple/blob/ios/3.5.0-373/Application/Sources/Content/SectionViewController.swift), without any top-level SwiftUI wrapping, though (as we manage the navigation entirely in UIKit), so I can provide you with hints about how this can be achieved.

**Comment by Jinya** [comment]
I do agree with your consideration of `UICollectionViewCompositionalLayout`. Its key role is to simplify the process of building a single `UICollectionView` which can contain lots of nested groups with just a small and robust amount of codes, instead of nesting many `UICollectionView` subclasses into the parent container as most developers did before iOS13.

However, these nested groups's layout can only be described on absolute or regular relative sizes,  isolated from the cell item data source, and actually it's layout looks like a set of `UICollectionViewFlowLayout` implementations

So the way to achieve Pinterest-style collection view layout in SwiftUI:
1. Create a `UICollectionViewLayout` custom subclass and implement custom cell layoutAttributes provider, e.g., [CHTCollectionViewWaterfallLayout](https://github.com/chiahsien/CHTCollectionViewWaterfallLayout).
2. Integrate the custom layout with `UIViewRepresentable`, and expose the data source and cell view content provider to SwiftUI.
3. Optimize the data source diff process.

**Comment by defagos** [comment]
Yes, that means you cannot use compositional layouts and that you cannot use my SwiftUI collection view implementation as it is currently implemented.

Moreover, and though wrapping a `UICollectionView` into SwiftUI is fun and insightful, it is much simpler, safer and efficient to avoid it IMHO. This is something I want to write an article about in the future, but the issue with wrapping a heavy component like `UICollectionView` into a SwiftUI view (and exposing data source and cell providers to SwiftUI) is that this requires optimization tricks to mitigate the cost of applying incremental changes. Not to mention that you somehow must persist the state during the lifetime of the SwiftUI view with a coordinator, which also requires some tricks.

What I therefore prefer to do nowadays:

1. Create a view controller displaying the `UICollectionView`.
2. Create a cell provider and assign the layout in the view controller implementation (e.g. with a custom layout or a declarative compositional layout).
3. Have the view controller own a diffable data source to drive collection view updates in a reactive manner.
3. Instantiate a view model in the view controller and respond to its updates by applying corresponding snapshots to the diffable data source. I usually implement the view model as an `ObservableObject`, register to some `@Published` property publisher which broadcasts view model updates, and apply the data source snapshot when an update is received (with a `sink`).

Of course this view controller itself can be wrapped into a `UIViewControllerRepresentable` to be inserted into SwiftUI view hierarchies directly. But the idea is not to define the collection view itself in a declarative manner in SwiftUI code: Though this is tempting (and fun) there are definitely pitfalls which, after more careful consideration, are probably not worth the trouble.

**Comment by Jinya** [comment]
Considering these existing SwiftUI View lifecycle management issues(such as the fake `onAppear`), `UIViewControllerRepresentable` is better than `UIViewRepresentable`. 

Moreover, after writing a series of SwiftUI code, considering the increasing cost and its limited capability, I actually should not use SwiftUI as the main entry of an app, but use traditional AppDelegate and ViewController as entry and 
view container, then use HostingController to embed various SwiftUI Views into the parent container.
