### ISSUE TITLE
Grid layout

### ISSUE THREAD

**Issue by danielsaidi** [defagos/SwiftUICollection#2]
As I wrote in the previous issue, I love this implementation and the demo app. Have you given any thoughts to how to reuse most of the implementation and instead apply a vertically scrolling grid layout?

I'm not sure that the underlying collection view would be the same though, since you would probably not want to expose the section configuration in the same way, but instead insert either item size or number of columns?

**Comment by defagos** [comment]
Hi again,

The collection implementation is generic, so achieving a vertically scrolling grid layout is only a matter of compositional layout definition. I am in fact implementing a vertical grid with the same `CollectionView` [at the moment](https://github.com/SRGSSR/playsrg-apple/blob/feature/show-page/TV%20Application/Sources/ShowDetailView.swift) (link can break in the future as it belongs to a feature branch, but code will sooner or later end on `develop`) . 

It suffices to define a single section and to put all items there, e.g.

```swift
private static func layoutSection() -> NSCollectionLayoutSection {
    let itemSize = NSCollectionLayoutSize(widthDimension: .fractionalWidth(1), heightDimension: .fractionalHeight(1))
    let item = NSCollectionLayoutItem(layoutSize: itemSize)
    item.contentInsets = NSDirectionalEdgeInsets(top: 20, leading: 20, bottom: 20, trailing: 20)
    
    let groupSize = NSCollectionLayoutSize(widthDimension: .fractionalWidth(1), heightDimension: .absolute(400))
    let group = NSCollectionLayoutGroup.horizontal(layoutSize: groupSize, subitem: item, count: 4)
    
    return NSCollectionLayoutSection(group: group)
}
```

Here I configured the grid with some padding around items, a height of 400 points, and 4 items per column, but of course you can create more elaborate layouts.

Here is the result I get with the layout definition above (no more individual scrolling, the grid is a vertical one):

![grid](https://user-images.githubusercontent.com/170201/98687271-d78fdd00-2369-11eb-9f54-4c1d6326c4e6.jpg)

Hope this helps!

**Comment by danielsaidi** [comment]
Aha, ok! Wow, you are using parts of collection view that I've never used! I'm very impressed!

I took your advice and didn't use this repo as a library, but rather started breaking up the code into multiple files as a way for me to read and understand it piece by piece. I was under the impression that I should create a new collection view and reuse some common parts, but now I take it that I should rather just provide the already existing collection view with another section layout provider?

I've started pushing the code to a library of my own (with credits and links to you and this repo of course), but perhaps this approach exposes too much if we can achieve various layouts with the same collection view? However, if you want me to create a PR with these changes, just let me know: https://github.com/danielsaidi/SwiftUIKit/tree/master/Sources/SwiftUIKit/Views/Collections

I'd be very interested in the final grid result :)

**Comment by danielsaidi** [comment]
Ok, I have started playing around with encapsulating your layouts in reusable types. For instance, by having this:

```
public struct CollectionViewLayout {
    
    var sectionLayoutProvider: (Int, NSCollectionLayoutEnvironment) -> NSCollectionLayoutSection
}
```

we could create pre-configured layouts, like your catalog layout:

```
public extension CollectionViewLayout {
    
    /**
     This layout makes a `CollectionView` render itself as a
     vertical list with horizontally scrolling rows.
     */
    static func catalog(
        itemSize: CGSize = CGSize(width: 200, height: 200),
        headerHeight: CGFloat = 44,
        sectionInsets: NSDirectionalEdgeInsets = NSDirectionalEdgeInsets(top: 20, leading: 0, bottom: 20, trailing: 0),
        itemSpacing: CGFloat = 60) -> CollectionViewLayout {
        CollectionViewLayout { sectionIndex, layoutEnvironment in
            let itemLayoutSize = NSCollectionLayoutSize(widthDimension: .fractionalWidth(1), heightDimension: .fractionalHeight(1))
            let item = NSCollectionLayoutItem(layoutSize: itemLayoutSize)
            let groupSize = NSCollectionLayoutSize(widthDimension: .absolute(itemSize.width), heightDimension: .absolute(itemSize.height))
            let group = NSCollectionLayoutGroup.horizontal(layoutSize: groupSize, subitems: [item])
            let header = NSCollectionLayoutBoundarySupplementaryItem(
                layoutSize: NSCollectionLayoutSize(widthDimension: .fractionalWidth(1), heightDimension: .absolute(headerHeight)),
                elementKind: UICollectionView.elementKindSectionHeader,
                alignment: .topLeading
            )
            
            let section = NSCollectionLayoutSection(group: group)
            section.contentInsets = sectionInsets
            section.interGroupSpacing = itemSpacing
            section.orthogonalScrollingBehavior = .continuous
            section.boundarySupplementaryItems = [header]
            return section
        }
    }
}
```

We can then apply the layout with a new `CollectionView` initializer:

```
public init(
    rows: [CollectionViewRow<Section, Item>],
    layout: CollectionViewLayout,
    @ViewBuilder cell: @escaping (IndexPath, Item) -> Cell,
    @ViewBuilder supplementaryView: @escaping (String, IndexPath) -> SupplementaryView) {
    self.cell = cell
    self.rows = rows
    self.sectionLayoutProvider = layout.sectionLayoutProvider
    self.supplementaryView = supplementaryView
}
```

and create our collection view like this:

```
var body: some View {
    CollectionView(rows: rows, layout: .catalog(), cell: myCell, supplementaryView: mySection)
```

This works great, so I'll try to create a grid layout as well, using your sample code.

**Comment by danielsaidi** [comment]
Ok, so this is pretty nice...from your `Shelf` view:

```
var body: some View {
    CollectionView(rows: rows, layout: .catalog, cell: cell, supplementaryView: supplementaryView)
        .frame(maxWidth: .infinity, maxHeight: .infinity)
        .ignoresSafeArea(.all)
}
    
func cell(indexPath: IndexPath, item: String) -> some View {
    GeometryReader { geometry in
        Button(action: shuffle) {
            ...
            .cardButtonStyle()
        }
    }
}
    
func supplementaryView(kind: String, indexPath: IndexPath) -> some View {
    HStack {
        Text("Section \(indexPath.section)")
        Spacer()
    }
}
```

I will try to create a grid layout with the code you posted above as well :)

**Comment by danielsaidi** [comment]
Ok, the vertical grid layout is done!

```
public extension CollectionViewLayout {
    
    /**
     This layout makes a `CollectionView` render itself as a
     vertical grid with `itemsPerRow` items per grid row.
     */
    static func verticalGrid(
        itemsPerRow: Int,
        itemHeight: CGFloat = 200,
        itemInsets: NSDirectionalEdgeInsets = NSDirectionalEdgeInsets(top: 20, leading: 20, bottom: 20, trailing: 20)) -> CollectionViewLayout {
        CollectionViewLayout { sectionIndex, layoutEnvironment in
            let layoutSize = NSCollectionLayoutSize(widthDimension: .fractionalWidth(1), heightDimension: .fractionalHeight(1))
            let layoutItem = NSCollectionLayoutItem(layoutSize: layoutSize)
            layoutItem.contentInsets = itemInsets
            let groupSize = NSCollectionLayoutSize(widthDimension: .fractionalWidth(1), heightDimension: .absolute(itemHeight))
            let group = NSCollectionLayoutGroup.horizontal(layoutSize: groupSize, subitem: layoutItem, count: itemsPerRow)
            return NSCollectionLayoutSection(group: group)
        }
    }
}
```

Which I apply in the same way as the `.catalog` style:

```
var body: some View {
    CollectionView(rows: rows, layout: .verticalGrid(itemsPerRow: 4), cell: cell, supplementaryView: supplementaryView)
        .frame(maxWidth: .infinity, maxHeight: .infinity)
        .ignoresSafeArea(.all)
}
```

The result is just amazing and renders super fast even though I fetch 1000x1000 pixel large images without downsampling:

<img width="1800" alt="image" src="https://user-images.githubusercontent.com/429927/98726068-4a16b200-2396-11eb-9261-6f8c69885ac7.png">

**Comment by defagos** [comment]
Glad you made it work! If this is ok for you I propose we close this issue (except if you still want to add something, of course).

**Comment by danielsaidi** [comment]
Yes, let's do so :) I have pushed to https://github.com/danielsaidi/SwiftUIKit/tree/master/Sources/SwiftUIKit/Views/Collections so please grab any parts that you think look good.
