### ISSUE TITLE
Lazy loading

### ISSUE THREAD

**Issue by danielsaidi** [defagos/SwiftUICollection#3]
Hi again! Sorry for spamming, but I thought I'd add issues here as I work with your amazing collection view and write about any findings I have when trying to solve them.

I actively work with this issue, so if you prefer that I don't create issues here (since for instance lazy loading is not part of your code) just let me know and I'll create issues in my own repo instead. I however gladly take any ideas you may have :)

So, I need lazy loading in my app and used to inject triggers into the cells `onAppear`, but had problems with `CollectionView` getting big gaps in the list when updating rows and items. Also, lazy loading did not always trigger.

I've therefore tried adding lazy loading to `CollectionView` and its `Coordinator`, but the problem still remains. Am I doing something wrong here?

In `Coordinator`, I inject a lazy load action and a trigger:

```
init(
    lazyLoadFunction: @escaping () -> Void,
    lazyLoadTrigger: @escaping (IndexPath) -> Bool) {
    self.lazyLoadFunction = lazyLoadFunction
    self.lazyLoadTrigger = lazyLoadTrigger
}

private let lazyLoadFunction: () -> Void
private let lazyLoadTrigger: (IndexPath) -> Bool
```

You can inject a lazy load action when creating a `CollectionView`:

```
public init(
        rows: [CollectionViewRow<Section, Item>],
        layout: CollectionViewLayout,
        lazyLoadAction: @escaping () -> Void = {} ...
```

and `CollectionView` then injects it into its `Coordinator`

```
public func makeCoordinator() -> Coordinator {
    Coordinator(lazyLoadFunction: lazyLoadAction, lazyLoadTrigger: shouldTriggerLazyLoad)
}
```

where the `shouldTriggerLazyLoad` trigger is just a function that checks if displaying a cell should trigger lazy load:

```
func shouldTriggerLazyLoad(forItemAt indexPath: IndexPath) -> Bool {
    let rowCount = rows.count
    let hasManySections = rowCount > 1
    let isLastRow = indexPath.section == rowCount - 1
    let isFirstItem = indexPath.row == 0
    if hasManySections { return isLastRow && isFirstItem }
    let itemCount = rows.last?.items.count ?? 0
    let isLastItem = indexPath.row == itemCount - 1
    return isLastItem
}
```

The code above is a bit hacky for now, but basically my intention is to either:

* Lazy load new rows when the last row is displayed in a multi-row collection
* Lazy load new items when the last item is displayed in a single-row collection

The lazy load trigger works as intended in your example, where I don't actually lazy load any new content. I just verify that the trigger works for the catalog and grid layouts. However, after lazy loading new content, the trigger randomly stops working.

**Comment by danielsaidi** [comment]
As I wrote above, I actively work with these issues as well, so if you prefer that I don't create issues here (since for instance lazy loading is not part of your code) just let me know and I'll create issues in my own repo instead.

**Comment by defagos** [comment]
Hi!

Not a problem, we can of course discuss other ideas or implementation details here, this is after all what this repository is about.

Could you define what you mean by _lazy loading_? The collection view already loads items on the fly (since this is what `UICollectionView` does under the hood). Are you therefore talking about loading more pages of items as you reach collection boundaries? 

If yes, this is something I implemented yesterday, borrowing an idea from [Donny Wals](https://www.donnywals.com/implementing-an-infinite-scrolling-list-with-swiftui-and-combine/) to trigger the mechanism on cell appearance for cells near the end of the list. With this idea I had no problem achieving proper behavior, as data source diffing will take care of adding items at the end of the collection.

**Comment by danielsaidi** [comment]
Oh sorry for being so vague. I mean just that, that the client should load more content and inject it into the current collection view's data as the user scrolls to end. I manage to get the first next page loaded, but as I then scroll to the end of the list that now is expanded with more items, nothing more happens.

As I wrote above, I handle this differently for the two different layouts. When you are scrolling vertically through many rows as in the catalog layout, you want to lazy load more content when the last (or one of the last) row is displayed, but for a grid layout that displays one row, you instead want to load more content when the last (or one of the last) item is displayed.

I'd love to take a look at what you've built!

**Comment by defagos** [comment]
Well, then this is exactly [what we do for the grid in our app](https://github.com/SRGSSR/playsrg-apple/blob/feature/show-page/TV%20Application/Sources/ShowDetailModel.swift#L30-L75). 

Our model exposes a method to trigger additional page retrieval on [cell appearance](https://github.com/SRGSSR/playsrg-apple/blob/feature/show-page/TV%20Application/Sources/ShowDetailView.swift#L73-L75). Only the last cell can trigger such a retrieval in our current implementation. Additional results are appended to the existing available ones and packaged as row for the collection, at which point the model is updated and updates are published.

The collection observes the model and therefore automatically adds new items at the bottom.

A similar approach could of course be applied for shelves in a catalog layout, though we don't at the moment.

**Comment by danielsaidi** [comment]
I have other problems with async data as well. Not just when lazy loading at the end of a list, but also when loading rows with multiple async requests.

Since I load my rows async, they can arrive out of order. I will then put them in order when I display them. Now, say that I load 5 rows and row 3, 4 and 5 comes back first, which cause them to appear on screen. The supplementary items show the name of the list for each row. I then get back 1 and 2 and put them at the beginning of the row list, which cause the collection view to be reloaded.

Now, the supplementary titles do not update until I scroll them out of the screen, then back in.

**Comment by defagos** [comment]
Well, stupid question, but if your requests are async, are you sure all UI updates are triggered from the main thread?

**Comment by danielsaidi** [comment]
There are no stupid questions! :D Yes, I pop all network requests back on the main thread.

**Comment by danielsaidi** [comment]
Hi @defagos - I finally had time to look into this problem.

In my app, I wrap the `CollectionView` within a `MovieGridView`, which I setup like this:

```
struct MovieGrid: View, Localized {
    
    init(
        movies: [Movie],
        lazyLoadAction: () -> Void,
        ....
```

I then create rows like this

```
var rows: [Row] { [Row(section: 0, items: movies)] }
```

and the collection view like this:

```
@ViewBuilder
private var content: some View {
    CollectionView(
        rows: rows,
        ... 
    }
```

I first populate the grid with `20` items. The lazy load action is injected into the grid and is triggered when the last movie cell appears. This loads more movies, which are used together with the original collection to create a new grid.

However, if I now scroll down to the end of this new list, no new pagination is performed. I tried checking what happens and noticed that the lazy load action still thinks that `movies` is the initial `20` collection and printing `self.movies.count` while debugging says `20`...while in fact the new grid has `40` movies.

If I add tap actions to the movie cells and print `movies.count` on tap, the print says `20`. However, If I add an extra button outside of the collection view and add the same tap action, the print says `40`. This is true for all cells in the collection, not only for the first batch of cells.

So, since the cells are reused within the collection view, it seems like the original set of cells that are reused keep a reference to the original grid, instead of the last created one.

Did you notice this when implementing lazy load in your app? Any idea how to solve it?

**Comment by defagos** [comment]
Hi! Not sure this is related to the collection. I don’t see your how your model is implemented here. Is it an `ObservableObject` and do your `rows` array and your SwiftUI view hierarchy get updated in response to the observed object publishing new changes?

**Comment by danielsaidi** [comment]
I've tried with having `movies` being a plain var (the state is kept outside the grid, though), making it a `@State` as well as wrapping the list in an `@ObservableObject` object...nothing works.

**Comment by danielsaidi** [comment]
The view that owns the grid keeps its movies in a pagination context:

```
@StateObject var paginationContext = PaginationContext<Movie>()
```

which it changes every time a pagination occurs. Since the grid is created with this context's movies, it recreated every time the context changes.

However, since the cells are created together with the first grid, I suspect that they are referring to the first grid even though they are used in the new grid. 

I will try injecting the context instead of the movies.

**Comment by danielsaidi** [comment]
Injecting the observable context instead of the movie list works!

So, instead of

```
struct MovieGrid: View, Localized {
    
    init(
        movies: [Movie],
        ...
    }
    
    private var movies: [Movie] { paginationContext.items ?? [] }
    ...
```

I now inject the state object from above:

```
struct MovieGrid: View, Localized {
    
    init(
        context: PaginationContext<Movie>,
        ...
    }
    
    private var paginationContext: PaginationContext<Movie>
```

This makes the dequeued cells refer to the same context instead of the initial movie collection.

**Comment by danielsaidi** [comment]
I'm closing this.
